### ISSUE TITLE
Doesn't work at all on mac

### ISSUE THREAD

**Issue by sjmills** [Peppie84/FS22_HudColor#4]
1. Change the color.
2. Save.
3. Quit.
4. Launch and load the same savegame. Defaults back to blue.

**Comment by Peppie84** [comment]
Hi @sjmills , thanks for your post. But please give me some more information.

- Do you have errors on your log file related to this mod?
- How much mods do you use?
- Do you have also that issue with a savegame and only this mod?
  - If it works, can you start a new savegame with all your mods and disable the other one by one, to find the faulty mod that prevents this mod to work correctly

Thanks

**Comment by sjmills** [comment]
I found an error in the log:

2024-07-11 08:19   Error: Could not save xml file 'settingsXML' to '/Users/tut/Library/Application Support/FarmingSimulator2022/modSettings/FS22_HudColor/../hudcolor.xml'

Looks like you're trying to save the file in modSettings rather than in modSettings/FS22_HudColor. This is a Mac, but it shouldn't make any difference. I'm wondering if the lua file path code fails because it can't find FS22_HudColor, so it can't go back down the path to modSettings. I'd have the mod create that folder and put the file in there instead, or build the path differently, like:

getUserProfileAppPath().."modSettings/hudcolor.xml";

**Comment by Peppie84** [comment]
Hi @sjmills thanks for your help. I've changed the base path to:
```lua
MOD_SETTINGS_DIRECTORY = getUserProfileAppPath() .. 'modSettings/',
```

Here is a generated dev-release with this fix. Can you confirm that the issue is fixed by that.
[FS22_HudColor.zip](https://github.com/user-attachments/files/16178693/FS22_HudColor.zip)

**Comment by sjmills** [comment]
That fixed it. Thanks for letting me confirm it.
